Name:           ros-indigo-ypspur
Version:        0.2.0
Release:        0%{?dist}
Summary:        ROS ypspur package

Group:          Development/Libraries
License:        MIT
URL:            https://openspur.org/redmine/projects/ypspur
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-indigo-catkin
BuildRequires:  automake
BuildRequires:  cmake
BuildRequires:  git
BuildRequires:  libtool
BuildRequires:  libtool-ltdl-devel

%description
YamabicoProject-Spur (YP-Spur) is A is developed with Intelligent Robot
Laboratory based on SH-Spur.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Fri Nov 06 2015 Daiki Maekawa <d.maekawa@rapyuta-robotics.com> - 0.2.0-0
- Autogenerated by Bloom

* Wed Oct 28 2015 Daiki Maekawa <d.maekawa@rapyuta-robotics.com> - 0.1.1-0
- Autogenerated by Bloom

* Fri Oct 16 2015 Daiki Maekawa <d.maekawa@rapyuta-robotics.com> - 0.0.1-4
- Autogenerated by Bloom

* Fri Sep 18 2015 Daiki Maekawa <d.maekawa@rapyuta-robotics.com> - 0.0.1-3
- Autogenerated by Bloom

* Wed Sep 16 2015 Daiki Maekawa <d.maekawa@rapyuta-robotics.com> - 0.0.1-2
- Autogenerated by Bloom

* Mon Sep 14 2015 Daiki Maekawa <d.maekawa@rapyuta-robotics.com> - 0.0.1-1
- Autogenerated by Bloom

* Mon Sep 14 2015 Daiki Maekawa <d.maekawa@rapyuta-robotics.com> - 0.0.1-0
- Autogenerated by Bloom

